### ISSUE TITLE
404 site not found

### ISSUE THREAD

**Issue by DinoBarton** [cpl-makerlab/simple-website-template#24]
There is a 404 message on the site.

![Screenshot 2024-08-09 at 13 56 36](https://github.com/user-attachments/assets/0b4348af-bd99-4b96-bc37-3642b9c0dd70)

**Comment by zirafa** [comment]
Thanks, it was a typo, should be fixed now. The correct URL is:

https://cplmakerlab.github.io/simple-website-template
